Toolbar integration
cosmocode/dokuwiki-plugin-doi pull request #2
Opened 2023-07-31 09:30 UTC by annda

Adds simple buttons for inserting `<doi>` and `<isbn>` syntax.

The icons in the DOI dropdown are just favicons from the respective ID resolver websites:

![image](https://github.com/cosmocode/dokuwiki-plugin-doi/assets/17853330/deac85f6-fc9b-4ca0-b56a-ac70503d5fdf)

I'm not sure if the icons are recognizable for the users? Any suggestions?

2023-07-31 14:48 UTC, splitbrain commented
DOIs and ISBNs are easily distinguishable from each other (one having a slash, the other consisting of `[0-9Xx]{10|13}`. So I don't think needing two separate buttons is needed. Instead the an approach similar to the vshare plugin could ask for the identifier and then insert the correct syntax.

2023-08-07 07:16 UTC, splitbrain requested changes

2023-08-07 07:16 UTC, splitbrain commented on script.js
> +        const isbnRegex = new RegExp('^(?=(?:\\D*\\d){10}(?:(?:\\D*\\d){3})?$)[\\d-]+$', 'i');
This seems not to match any ISBNs ending in X

https://regex101.com/r/NOZNF9/2

2023-08-07 07:16 UTC, splitbrain commented on img/doi.png
no longer needed?

2023-08-07 07:16 UTC, splitbrain commented on img/ISBN.png
no longer needed?

2023-08-07 07:16 UTC, splitbrain commented on style.less
> +}
I think this is obsolete as well?

2023-08-07 11:29 UTC, merged

2023-08-07 11:30 UTC, annda commented on script.js
> +        const isbnRegex = new RegExp('^(?=(?:\\D*\\d){10}(?:(?:\\D*\\d){3})?$)[\\d-]+$', 'i');
Fixed: https://regex101.com/r/NOZNF9/3